version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8010:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
      - ./server:/var/www/:delegated
    depends_on:
      - php

  php:
    container_name: php-laravel_other
    build: ./php
    volumes:
      - ./server:/var/www/:delegated
